version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - CAT_API_URL=https://cataas.com/cat
    volumes:
      - ./app/.env:/app/.env  # Mount backend .env
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000/v1
    volumes:
      - ./frontend/.env:/app/.env  # Mount frontend .env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge